First version
it-at-m/digiwf-spring-cloudstream-utils pull request #1
Opened 2022-03-11 09:54 UTC by axd4

First version of the digiwf-spring-cloudstream-utils library

2022-03-15 11:09 UTC, dominikhorn93 requested changes

2022-03-15 11:09 UTC, dominikhorn93 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +
Remove line break? Same style as above

2022-03-15 11:09 UTC, dominikhorn93 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +        final Sinks.EmitResult emitResult = this.messageSink.tryEmitNext(message);
We should discuss if we want to go blocking with `tryEmitNext` or if we want to use non-blocking `emitNext` and pass a `EmitFailureHandler` as second parameter. @xdoo what do you think?

2022-03-15 11:09 UTC, dominikhorn93 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
we need the same plugins as here: https://github.com/it-at-m/digiwf-s3-integration/blob/dev/pom.xml for releasing it in maven central

2022-03-15 11:10 UTC, dominikhorn93 commented
Great work! 👍  Have some small change requests.

2022-03-15 12:07 UTC, axd4 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/EventEmitter.java
> +public class EventEmitter {
Can just call it MessageEmitter too. We don't really need Event here imo, my bad :)

2022-03-15 15:45 UTC, axd4 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +        Map<String, Object> headers = new HashMap<>();
Done

2022-03-15 15:46 UTC, axd4 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +
Done

2022-03-15 15:46 UTC, axd4 commented on README.md
> +<div id="top"></div>
Thanks! ❤️

2022-03-15 22:05 UTC, dominikhorn93 commented on digiwf-spring-cloudstream-utils-starter/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/configuration/StreamingConfiguration.java
> +        return new MessageRoutingCallback() {
Almost 🚀 

Would do it this way:

```
@RequiredArgsConstructor
public class RoutingCallback implements MessageRoutingCallback {

    private final Map<String, String> typeMappings;

    @Override
    public FunctionRoutingResult routingResult(final Message<?> message) {
        final String functionDefinition;

        if (message.getHeaders().containsKey(StreamingHeaders.TYPE)) {
            final String header = (String) message.getHeaders().get(StreamingHeaders.TYPE);
            functionDefinition = this.typeMappings.getOrDefault(header, FUNCTION_ROUTING_ERROR);
        } else {
            functionDefinition = MISSING_TYPE_HEADER_ERROR;
        }

        return new FunctionRoutingResult(functionDefinition);
    }

}
```


```
@Configuration
@RequiredArgsConstructor
@ComponentScan(basePackages = "io.muenchendigital.digiwf.spring.cloudstream.utils")
@EnableConfigurationProperties(StreamingProperties.class)
public class StreamingConfiguration {

    private final StreamingProperties streamingProperties;

    @Bean
    public MessageRoutingCallback customRouter() {
        return new RoutingCallback(this.streamingProperties.getTypeMappings());
    }
}
```

2022-03-15 22:07 UTC, dominikhorn93 commented
@axd4 We should also add "real" Javadocs. But for that we can also create an issue. What do you think?

2022-03-16 09:27 UTC, axd4 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +
Done

2022-03-16 09:27 UTC, axd4 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Implemented, seems to work as expected.

2022-03-16 09:29 UTC, axd4 commented on digiwf-spring-cloudstream-utils-starter/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/configuration/StreamingConfiguration.java
> +        return new MessageRoutingCallback() {
Adopted your code

2022-03-16 09:31 UTC, axd4 commented
> @axd4 We should also add "real" Javadocs. But for that we can also create an issue. What do you think?

Let's do that in a new issue and merge the first version

2022-03-17 12:18 UTC, axd4 commented on digiwf-spring-cloudstream-utils/src/main/java/io/muenchendigital/digiwf/spring/cloudstream/utils/api/streaming/PayloadSender.java
> +        final Sinks.EmitResult emitResult = this.messageSink.tryEmitNext(message);
See #3

2022-03-17 12:19 UTC, dominikhorn93 approved these changes

2022-03-17 12:21 UTC, merged